ODS HTML path="&G_PING_RAWDB/&cc./&ss&yy/" body="followup.html" style=EGdefault nogtitle;
TITLE;

libname lib "&G_PING_RAWDB/&cc./&ss&yy";

PROC TABULATE
DATA=lib.&ss.&cc.&yy.d;
	CLASS DB010 /	ORDER=UNFORMATTED MISSING;
	CLASS DB075 /	ORDER=UNFORMATTED MISSING;
	CLASS DB020;
	TABLE DB020="", DB010="", (DB075 all)*(RowPctN  N)
		/BOX={LABEL=_PAGE_ STYLE={FONT_SIZE=6}};
RUN;

PROC TABULATE
DATA=lib.&ss.&cc.&yy.d;
	CLASS DB010 /	ORDER=UNFORMATTED MISSING;
	CLASS DB110 /	ORDER=UNFORMATTED MISSING;
	CLASS DB020;
	TABLE DB020="", DB010="", DB110*(RowPctN  N)
		/BOX={LABEL=_PAGE_ STYLE={FONT_SIZE=6}};
RUN;

PROC TABULATE
DATA=lib.&ss.&cc.&yy.r;
	CLASS RB010 /	ORDER=UNFORMATTED MISSING;
	CLASS RB110 /	ORDER=UNFORMATTED MISSING;
	CLASS RB020;
	TABLE RB020="", RB010="", RB110*(RowPctN  N)
		/BOX={LABEL=_PAGE_ STYLE={FONT_SIZE=6}};
RUN;

ODS HTML CLOSE;
